version: "2.1"

volumes:
  # **balena-pihole**
  pihole_config: {}
  dnsmasq_config: {}
  # tailscale: {}
  # **balena-sound**
  spotifycache:

services:
  # **balena-pihole**
  # https://hub.docker.com/r/pihole/pihole
  pihole:
    build: balena-pihole/pihole
    cap_add:
      - SYS_TTY_CONFIG
      - NET_ADMIN
    volumes:
      - "pihole_config:/etc/pihole"
      - "dnsmasq_config:/etc/dnsmasq.d"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    network_mode: host
    labels:
      io.balena.features.dbus: "1"
    devices:
      - /dev/tty0
      - /dev/tty1
    tmpfs:
      - /var/log/pihole
    environment:
      DNSMASQ_LISTENING: all
      # PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      FONTFACE: Terminus
      FONTSIZE: 8x14
      # WEBPASSWORD: balena
      VIRTUAL_HOST: balena-devices.com
      WEB_BIND_ADDR: 0.0.0.0

  # https://github.com/klutchell/unbound-dnscrypt
  # Recursive DNS, not used
  # unbound:
  #   build: unbound
  #   cap_add:
  #    - NET_ADMIN
  #   ports:
  #     - "5053:5053/tcp"
  #     - "5053:5053/udp"

  # https://github.com/balena-labs-projects/fbcp
  # https://hub.balena.io/blocks/1792683/fbcp
  # Display driver, not used
  # fbcp:
  #   image: bh.cr/balenalabs/fbcp/1.0.4
  #   privileged: true

  # https://github.com/klutchell/balena-tailscale
  # Tailscale VPN, not used
  # tailscale:
  #   build: balena-pihole/tailscale
  #   network_mode: host
  #   restart: on-failure
  #   volumes:
  #     - tailscale:/var/lib/tailscale
  #   labels:
  #     - io.balena.features.kernel-modules=1
  #   cap_add:
  #     - net_admin
  #     - net_raw
  #     - sys_module
  #   tmpfs:
  #     - /tmp
  #     - /var/run/
  #   environment:
  #     TS_EXTRA_ARGS: --accept-dns=false --reset
  #     REQUIRE_AUTH_KEY: "true"
  
  # https://github.com/balenablocks/hostname
  # https://hub.balena.io/blocks/1918776/hostname-rpi
  hostname:
    image: bh.cr/g_tomas_migone1/hostname-rpi/0.2.1
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: holysound
  
  # **balena-sound**
  # Core services
  # -- Required for a fully featured installation of balenaSound
  # -- Mutiroom services can be removed if not using multiroom mode
  audio:
    build: balena-sound/core/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - 4317:4317

  sound-supervisor:
    build:
      context: balena-sound
      dockerfile: core/sound-supervisor/Dockerfile.template
    network_mode: host
    labels:
      io.balena.features.balena-api: "1"
      io.balena.features.supervisor-api: 1

  # Disable Multiroom with SOUND_MODE=STANDALONE
  # See https://sound.balenalabs.io/docs/customization/
  multiroom-server:
    build: balena-sound/core/multiroom/server
    restart: on-failure
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780

  multiroom-client:
    build: balena-sound/core/multiroom/client
    restart: on-failure

  # Plugins
  # -- Additional plugins can be added. See https://sound.balenalabs.io/docs/plugins.
  # -- Remove unwanted plugins as needed
  bluetooth:
    build: balena-sound/plugins/bluetooth
    restart: on-failure
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1

  airplay:
    build: balena-sound/plugins/airplay
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1

  spotify:
    build: balena-sound/plugins/spotify
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - spotifycache:/var/cache/raspotify
